### You still doesn't write comments for this notebook...

In [3]:
import numpy as np

In [4]:
# Initialize the parameters
def config():
    conf = {}
    conf['input_size'] = 42
    conf['output_size'] = 1
    conf['learning_rate'] = float(input("say the learning rate:"))
    conf['activation'] = input("what is activation function?")
    conf['batch'] = int(input("say batch size:"))
    conf['n_iter'] = int(input("say number of iterations:"))
    conf['n_layers'] = int(input("say number of layers:"))
    for i in range(conf['n_layers'] - 2):
        conf['neuron{}'.format(i)] = int(input("say the number of neurons of {}th hidden layer:"\
                                              .format(i)))
    return conf

In [13]:
class Layer():
    def __init__():
        self.input = None
        self.output = None
    
    def forward(self, input):
        # Do feed-forward and return output
        pass
    
    def backward(self, output_gradient, learning_rate):
        # Do back propagation. Update traineble parameters and return input gradient.
        pass
    

In [35]:
class Dense(Layer):
    def __init__(self, input_size, output_size):
        self.weights = np.random.randn(input_size, output_size)
        self.bias = np.random.randn(output_size, 1)
        
        
    def forward(self, input):
        self.input = input
        return np.dot(self.weights, self.input) + self.bias
    
    def backward(self, output_gradient, learning_rate):
        weights_gradient = np.dot(output_gradient, self.input.T)
        input_gradient = np.dot(self.weights.T, output_gradient)
        self.weights -= learning_rate * weights_gradient
        self.bias -= learning_rate * output_gradient
        return input_gradient
    

In [37]:
# Define activation functions for feedforward and backpropagation
class ReLU(Layer):
    def forward(self, x):
        self.input = x
        return x * (x > 0)
    
    def backward(self, grad_output):
        return grad_output * (self.input > 0)

class Sigmoid(Layer):
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def forward(self, x):
        self.input = x
        return self.sigmoid(x)
    
    def backward(self, grad_output):
        sigmoid_output = self.sigmoid(self.input)
        return grad_output * sigmoid_output * (1 - sigmoid_output)
    
class Softmax(Layer):
    
    def softmax(self, x):
        exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
        return exp_x / np.sum(exp_x, axis=-1, keepdims=True)
    
    def forward(self, x):
        self.input = x
        return self.softmax(x)
    
    def backward(self, grad_output):
        softmax_output = self.softmax(self.input)
        return grad_output * softmax_output * (1 - softmax_output)

In [9]:
data = np.load("./Data/x_10classes.npy")

In [29]:
data.shape

(20843, 42)

In [16]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

In [19]:
c = np.dot(a, b)

In [28]:
c[0][0]

4

In [26]:
a

array([[1, 0],
       [0, 1]])

In [27]:
b

array([[4, 1],
       [2, 2]])

In [30]:
X = np.reshape([[0, 0], [0, 1], [1, 0], [1, 1]], (4, 2, 1))
Y = np.reshape([[0], [1], [1], [0]], (4, 1, 1))

In [32]:
X.shape

(4, 2, 1)

In [33]:
Y.shape

(4, 1, 1)

In [34]:
X

array([[[0],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [1]]])